TOKEN = "7331184980:AAE3I8rBARE7F3vNFOVxyuf117a6sfStIDY"


MYSQL_HOST = "localhost"
MYSQL_USER = "root"
MYSQL_PASSWORD = "Aidai99!"
MYSQL_DB = "BOT"

MYSQL_URL = (f'mysql+aiomysql://{MYSQL_USER}:{MYSQL_PASSWORD}@{MYSQL_HOST}/{MYSQL_DB}')
